# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Docencia(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_docencia: int=None, id_profesor: int=None, id_grado_asignatura: int=None):
        """
        Docencia - a model defined in Swagger

        :param id_docencia: The id_docencia of this Docencia.
        :type id_docencia: int
        :param id_profesor: The id_profesor of this Docencia.
        :type id_profesor: int
        :param id_grado_asignatura: The id_grado_asignatura of this Docencia.
        :type id_grado_asignatura: int
        """
        self.swagger_types = {
            'id_docencia': int,
            'id_profesor': int,
            'id_grado_asignatura': int
        }

        self.attribute_map = {
            'id_docencia': 'id_docencia',
            'id_profesor': 'id_profesor',
            'id_grado_asignatura': 'id_gradoAsignatura'
        }

        self._id_docencia = id_docencia
        self._id_profesor = id_profesor
        self._id_grado_asignatura = id_grado_asignatura

    @classmethod
    def from_dict(cls, dikt) -> 'Docencia':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Docencia of this Docencia.
        :rtype: Docencia
        """
        return deserialize_model(dikt, cls)

    @property
    def id_docencia(self) -> int:
        """
        Gets the id_docencia of this Docencia.

        :return: The id_docencia of this Docencia.
        :rtype: int
        """
        return self._id_docencia

    @id_docencia.setter
    def id_docencia(self, id_docencia: int):
        """
        Sets the id_docencia of this Docencia.

        :param id_docencia: The id_docencia of this Docencia.
        :type id_docencia: int
        """

        self._id_docencia = id_docencia

    @property
    def id_profesor(self) -> int:
        """
        Gets the id_profesor of this Docencia.

        :return: The id_profesor of this Docencia.
        :rtype: int
        """
        return self._id_profesor

    @id_profesor.setter
    def id_profesor(self, id_profesor: int):
        """
        Sets the id_profesor of this Docencia.

        :param id_profesor: The id_profesor of this Docencia.
        :type id_profesor: int
        """

        self._id_profesor = id_profesor

    @property
    def id_grado_asignatura(self) -> int:
        """
        Gets the id_grado_asignatura of this Docencia.

        :return: The id_grado_asignatura of this Docencia.
        :rtype: int
        """
        return self._id_grado_asignatura

    @id_grado_asignatura.setter
    def id_grado_asignatura(self, id_grado_asignatura: int):
        """
        Sets the id_grado_asignatura of this Docencia.

        :param id_grado_asignatura: The id_grado_asignatura of this Docencia.
        :type id_grado_asignatura: int
        """

        self._id_grado_asignatura = id_grado_asignatura

