# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AsignaturaMatricula(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_matriculacion: str=None, numero_convocatoria: int=None, numero_matricula: int=None, nota: float=None, aprobado: bool=None, id_alumno: str=None, codigo_asignatura: str=None):
        """
        AsignaturaMatricula - a model defined in Swagger

        :param id_matriculacion: The id_matriculacion of this AsignaturaMatricula.
        :type id_matriculacion: str
        :param numero_convocatoria: The numero_convocatoria of this AsignaturaMatricula.
        :type numero_convocatoria: int
        :param numero_matricula: The numero_matricula of this AsignaturaMatricula.
        :type numero_matricula: int
        :param nota: The nota of this AsignaturaMatricula.
        :type nota: float
        :param aprobado: The aprobado of this AsignaturaMatricula.
        :type aprobado: bool
        :param id_alumno: The id_alumno of this AsignaturaMatricula.
        :type id_alumno: str
        :param codigo_asignatura: The codigo_asignatura of this AsignaturaMatricula.
        :type codigo_asignatura: str
        """
        self.swagger_types = {
            'id_matriculacion': str,
            'numero_convocatoria': int,
            'numero_matricula': int,
            'nota': float,
            'aprobado': bool,
            'id_alumno': str,
            'codigo_asignatura': str
        }

        self.attribute_map = {
            'id_matriculacion': 'id_matriculacion',
            'numero_convocatoria': 'numero_convocatoria',
            'numero_matricula': 'numero_matricula',
            'nota': 'nota',
            'aprobado': 'aprobado',
            'id_alumno': 'id_alumno',
            'codigo_asignatura': 'codigo_asignatura'
        }

        self._id_matriculacion = id_matriculacion
        self._numero_convocatoria = numero_convocatoria
        self._numero_matricula = numero_matricula
        self._nota = nota
        self._aprobado = aprobado
        self._id_alumno = id_alumno
        self._codigo_asignatura = codigo_asignatura

    @classmethod
    def from_dict(cls, dikt) -> 'AsignaturaMatricula':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Asignatura_Matricula of this AsignaturaMatricula.
        :rtype: AsignaturaMatricula
        """
        return deserialize_model(dikt, cls)

    @property
    def id_matriculacion(self) -> str:
        """
        Gets the id_matriculacion of this AsignaturaMatricula.

        :return: The id_matriculacion of this AsignaturaMatricula.
        :rtype: str
        """
        return self._id_matriculacion

    @id_matriculacion.setter
    def id_matriculacion(self, id_matriculacion: str):
        """
        Sets the id_matriculacion of this AsignaturaMatricula.

        :param id_matriculacion: The id_matriculacion of this AsignaturaMatricula.
        :type id_matriculacion: str
        """

        self._id_matriculacion = id_matriculacion

    @property
    def numero_convocatoria(self) -> int:
        """
        Gets the numero_convocatoria of this AsignaturaMatricula.

        :return: The numero_convocatoria of this AsignaturaMatricula.
        :rtype: int
        """
        return self._numero_convocatoria

    @numero_convocatoria.setter
    def numero_convocatoria(self, numero_convocatoria: int):
        """
        Sets the numero_convocatoria of this AsignaturaMatricula.

        :param numero_convocatoria: The numero_convocatoria of this AsignaturaMatricula.
        :type numero_convocatoria: int
        """

        self._numero_convocatoria = numero_convocatoria

    @property
    def numero_matricula(self) -> int:
        """
        Gets the numero_matricula of this AsignaturaMatricula.

        :return: The numero_matricula of this AsignaturaMatricula.
        :rtype: int
        """
        return self._numero_matricula

    @numero_matricula.setter
    def numero_matricula(self, numero_matricula: int):
        """
        Sets the numero_matricula of this AsignaturaMatricula.

        :param numero_matricula: The numero_matricula of this AsignaturaMatricula.
        :type numero_matricula: int
        """

        self._numero_matricula = numero_matricula

    @property
    def nota(self) -> float:
        """
        Gets the nota of this AsignaturaMatricula.

        :return: The nota of this AsignaturaMatricula.
        :rtype: float
        """
        return self._nota

    @nota.setter
    def nota(self, nota: float):
        """
        Sets the nota of this AsignaturaMatricula.

        :param nota: The nota of this AsignaturaMatricula.
        :type nota: float
        """

        self._nota = nota

    @property
    def aprobado(self) -> bool:
        """
        Gets the aprobado of this AsignaturaMatricula.

        :return: The aprobado of this AsignaturaMatricula.
        :rtype: bool
        """
        return self._aprobado

    @aprobado.setter
    def aprobado(self, aprobado: bool):
        """
        Sets the aprobado of this AsignaturaMatricula.

        :param aprobado: The aprobado of this AsignaturaMatricula.
        :type aprobado: bool
        """

        self._aprobado = aprobado

    @property
    def id_alumno(self) -> str:
        """
        Gets the id_alumno of this AsignaturaMatricula.

        :return: The id_alumno of this AsignaturaMatricula.
        :rtype: str
        """
        return self._id_alumno

    @id_alumno.setter
    def id_alumno(self, id_alumno: str):
        """
        Sets the id_alumno of this AsignaturaMatricula.

        :param id_alumno: The id_alumno of this AsignaturaMatricula.
        :type id_alumno: str
        """

        self._id_alumno = id_alumno

    @property
    def codigo_asignatura(self) -> str:
        """
        Gets the codigo_asignatura of this AsignaturaMatricula.

        :return: The codigo_asignatura of this AsignaturaMatricula.
        :rtype: str
        """
        return self._codigo_asignatura

    @codigo_asignatura.setter
    def codigo_asignatura(self, codigo_asignatura: str):
        """
        Sets the codigo_asignatura of this AsignaturaMatricula.

        :param codigo_asignatura: The codigo_asignatura of this AsignaturaMatricula.
        :type codigo_asignatura: str
        """

        self._codigo_asignatura = codigo_asignatura

