# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Departamento(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_departamento: int=None, nombre_departamento: str=None, descripcion_departamento: str=None, id_facultad: int=None):
        """
        Departamento - a model defined in Swagger

        :param id_departamento: The id_departamento of this Departamento.
        :type id_departamento: int
        :param nombre_departamento: The nombre_departamento of this Departamento.
        :type nombre_departamento: str
        :param descripcion_departamento: The descripcion_departamento of this Departamento.
        :type descripcion_departamento: str
        :param id_facultad: The id_facultad of this Departamento.
        :type id_facultad: int
        """
        self.swagger_types = {
            'id_departamento': int,
            'nombre_departamento': str,
            'descripcion_departamento': str,
            'id_facultad': int
        }

        self.attribute_map = {
            'id_departamento': 'id_departamento',
            'nombre_departamento': 'nombreDepartamento',
            'descripcion_departamento': 'descripcionDepartamento',
            'id_facultad': 'id_facultad'
        }

        self._id_departamento = id_departamento
        self._nombre_departamento = nombre_departamento
        self._descripcion_departamento = descripcion_departamento
        self._id_facultad = id_facultad

    @classmethod
    def from_dict(cls, dikt) -> 'Departamento':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Departamento of this Departamento.
        :rtype: Departamento
        """
        return deserialize_model(dikt, cls)

    @property
    def id_departamento(self) -> int:
        """
        Gets the id_departamento of this Departamento.

        :return: The id_departamento of this Departamento.
        :rtype: int
        """
        return self._id_departamento

    @id_departamento.setter
    def id_departamento(self, id_departamento: int):
        """
        Sets the id_departamento of this Departamento.

        :param id_departamento: The id_departamento of this Departamento.
        :type id_departamento: int
        """

        self._id_departamento = id_departamento

    @property
    def nombre_departamento(self) -> str:
        """
        Gets the nombre_departamento of this Departamento.

        :return: The nombre_departamento of this Departamento.
        :rtype: str
        """
        return self._nombre_departamento

    @nombre_departamento.setter
    def nombre_departamento(self, nombre_departamento: str):
        """
        Sets the nombre_departamento of this Departamento.

        :param nombre_departamento: The nombre_departamento of this Departamento.
        :type nombre_departamento: str
        """

        self._nombre_departamento = nombre_departamento

    @property
    def descripcion_departamento(self) -> str:
        """
        Gets the descripcion_departamento of this Departamento.

        :return: The descripcion_departamento of this Departamento.
        :rtype: str
        """
        return self._descripcion_departamento

    @descripcion_departamento.setter
    def descripcion_departamento(self, descripcion_departamento: str):
        """
        Sets the descripcion_departamento of this Departamento.

        :param descripcion_departamento: The descripcion_departamento of this Departamento.
        :type descripcion_departamento: str
        """

        self._descripcion_departamento = descripcion_departamento

    @property
    def id_facultad(self) -> int:
        """
        Gets the id_facultad of this Departamento.

        :return: The id_facultad of this Departamento.
        :rtype: int
        """
        return self._id_facultad

    @id_facultad.setter
    def id_facultad(self, id_facultad: int):
        """
        Sets the id_facultad of this Departamento.

        :param id_facultad: The id_facultad of this Departamento.
        :type id_facultad: int
        """

        self._id_facultad = id_facultad

