# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Profesor(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_profesor: int=None, puesto_profesor: str=None, categoria_profesor: str=None, dni_profesor: str=None, nombre_profesor: str=None, apellidos_profesor: str=None, fecha_comienzo_docencia: str=None, direccion_profesor: str=None, telefono_profesor: str=None, id_departamento: int=None):
        """
        Profesor - a model defined in Swagger

        :param id_profesor: The id_profesor of this Profesor.
        :type id_profesor: int
        :param puesto_profesor: The puesto_profesor of this Profesor.
        :type puesto_profesor: str
        :param categoria_profesor: The categoria_profesor of this Profesor.
        :type categoria_profesor: str
        :param dni_profesor: The dni_profesor of this Profesor.
        :type dni_profesor: str
        :param nombre_profesor: The nombre_profesor of this Profesor.
        :type nombre_profesor: str
        :param apellidos_profesor: The apellidos_profesor of this Profesor.
        :type apellidos_profesor: str
        :param fecha_comienzo_docencia: The fecha_comienzo_docencia of this Profesor.
        :type fecha_comienzo_docencia: str
        :param direccion_profesor: The direccion_profesor of this Profesor.
        :type direccion_profesor: str
        :param telefono_profesor: The telefono_profesor of this Profesor.
        :type telefono_profesor: str
        :param id_departamento: The id_departamento of this Profesor.
        :type id_departamento: int
        """
        self.swagger_types = {
            'id_profesor': int,
            'puesto_profesor': str,
            'categoria_profesor': str,
            'dni_profesor': str,
            'nombre_profesor': str,
            'apellidos_profesor': str,
            'fecha_comienzo_docencia': str,
            'direccion_profesor': str,
            'telefono_profesor': str,
            'id_departamento': int
        }

        self.attribute_map = {
            'id_profesor': 'id_profesor',
            'puesto_profesor': 'puestoProfesor',
            'categoria_profesor': 'categoriaProfesor',
            'dni_profesor': 'dniProfesor',
            'nombre_profesor': 'nombreProfesor',
            'apellidos_profesor': 'apellidosProfesor',
            'fecha_comienzo_docencia': 'fechaComienzoDocencia',
            'direccion_profesor': 'direccionProfesor',
            'telefono_profesor': 'telefonoProfesor',
            'id_departamento': 'id_departamento'
        }

        self._id_profesor = id_profesor
        self._puesto_profesor = puesto_profesor
        self._categoria_profesor = categoria_profesor
        self._dni_profesor = dni_profesor
        self._nombre_profesor = nombre_profesor
        self._apellidos_profesor = apellidos_profesor
        self._fecha_comienzo_docencia = fecha_comienzo_docencia
        self._direccion_profesor = direccion_profesor
        self._telefono_profesor = telefono_profesor
        self._id_departamento = id_departamento

    @classmethod
    def from_dict(cls, dikt) -> 'Profesor':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Profesor of this Profesor.
        :rtype: Profesor
        """
        return deserialize_model(dikt, cls)

    @property
    def id_profesor(self) -> int:
        """
        Gets the id_profesor of this Profesor.

        :return: The id_profesor of this Profesor.
        :rtype: int
        """
        return self._id_profesor

    @id_profesor.setter
    def id_profesor(self, id_profesor: int):
        """
        Sets the id_profesor of this Profesor.

        :param id_profesor: The id_profesor of this Profesor.
        :type id_profesor: int
        """

        self._id_profesor = id_profesor

    @property
    def puesto_profesor(self) -> str:
        """
        Gets the puesto_profesor of this Profesor.

        :return: The puesto_profesor of this Profesor.
        :rtype: str
        """
        return self._puesto_profesor

    @puesto_profesor.setter
    def puesto_profesor(self, puesto_profesor: str):
        """
        Sets the puesto_profesor of this Profesor.

        :param puesto_profesor: The puesto_profesor of this Profesor.
        :type puesto_profesor: str
        """

        self._puesto_profesor = puesto_profesor

    @property
    def categoria_profesor(self) -> str:
        """
        Gets the categoria_profesor of this Profesor.

        :return: The categoria_profesor of this Profesor.
        :rtype: str
        """
        return self._categoria_profesor

    @categoria_profesor.setter
    def categoria_profesor(self, categoria_profesor: str):
        """
        Sets the categoria_profesor of this Profesor.

        :param categoria_profesor: The categoria_profesor of this Profesor.
        :type categoria_profesor: str
        """

        self._categoria_profesor = categoria_profesor

    @property
    def dni_profesor(self) -> str:
        """
        Gets the dni_profesor of this Profesor.

        :return: The dni_profesor of this Profesor.
        :rtype: str
        """
        return self._dni_profesor

    @dni_profesor.setter
    def dni_profesor(self, dni_profesor: str):
        """
        Sets the dni_profesor of this Profesor.

        :param dni_profesor: The dni_profesor of this Profesor.
        :type dni_profesor: str
        """

        self._dni_profesor = dni_profesor

    @property
    def nombre_profesor(self) -> str:
        """
        Gets the nombre_profesor of this Profesor.

        :return: The nombre_profesor of this Profesor.
        :rtype: str
        """
        return self._nombre_profesor

    @nombre_profesor.setter
    def nombre_profesor(self, nombre_profesor: str):
        """
        Sets the nombre_profesor of this Profesor.

        :param nombre_profesor: The nombre_profesor of this Profesor.
        :type nombre_profesor: str
        """

        self._nombre_profesor = nombre_profesor

    @property
    def apellidos_profesor(self) -> str:
        """
        Gets the apellidos_profesor of this Profesor.

        :return: The apellidos_profesor of this Profesor.
        :rtype: str
        """
        return self._apellidos_profesor

    @apellidos_profesor.setter
    def apellidos_profesor(self, apellidos_profesor: str):
        """
        Sets the apellidos_profesor of this Profesor.

        :param apellidos_profesor: The apellidos_profesor of this Profesor.
        :type apellidos_profesor: str
        """

        self._apellidos_profesor = apellidos_profesor

    @property
    def fecha_comienzo_docencia(self) -> str:
        """
        Gets the fecha_comienzo_docencia of this Profesor.

        :return: The fecha_comienzo_docencia of this Profesor.
        :rtype: str
        """
        return self._fecha_comienzo_docencia

    @fecha_comienzo_docencia.setter
    def fecha_comienzo_docencia(self, fecha_comienzo_docencia: str):
        """
        Sets the fecha_comienzo_docencia of this Profesor.

        :param fecha_comienzo_docencia: The fecha_comienzo_docencia of this Profesor.
        :type fecha_comienzo_docencia: str
        """

        self._fecha_comienzo_docencia = fecha_comienzo_docencia

    @property
    def direccion_profesor(self) -> str:
        """
        Gets the direccion_profesor of this Profesor.

        :return: The direccion_profesor of this Profesor.
        :rtype: str
        """
        return self._direccion_profesor

    @direccion_profesor.setter
    def direccion_profesor(self, direccion_profesor: str):
        """
        Sets the direccion_profesor of this Profesor.

        :param direccion_profesor: The direccion_profesor of this Profesor.
        :type direccion_profesor: str
        """

        self._direccion_profesor = direccion_profesor

    @property
    def telefono_profesor(self) -> str:
        """
        Gets the telefono_profesor of this Profesor.

        :return: The telefono_profesor of this Profesor.
        :rtype: str
        """
        return self._telefono_profesor

    @telefono_profesor.setter
    def telefono_profesor(self, telefono_profesor: str):
        """
        Sets the telefono_profesor of this Profesor.

        :param telefono_profesor: The telefono_profesor of this Profesor.
        :type telefono_profesor: str
        """

        self._telefono_profesor = telefono_profesor

    @property
    def id_departamento(self) -> int:
        """
        Gets the id_departamento of this Profesor.

        :return: The id_departamento of this Profesor.
        :rtype: int
        """
        return self._id_departamento

    @id_departamento.setter
    def id_departamento(self, id_departamento: int):
        """
        Sets the id_departamento of this Profesor.

        :param id_departamento: The id_departamento of this Profesor.
        :type id_departamento: int
        """

        self._id_departamento = id_departamento

