# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Reserva(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_reserva: int=None, titulae_reserva: str=None, hora_inicio: str=None, hora_fin: str=None, fecha_reserva: str=None, id_medio: int=None):
        """
        Reserva - a model defined in Swagger

        :param id_reserva: The id_reserva of this Reserva.
        :type id_reserva: int
        :param titulae_reserva: The titulae_reserva of this Reserva.
        :type titulae_reserva: str
        :param hora_inicio: The hora_inicio of this Reserva.
        :type hora_inicio: str
        :param hora_fin: The hora_fin of this Reserva.
        :type hora_fin: str
        :param fecha_reserva: The fecha_reserva of this Reserva.
        :type fecha_reserva: str
        :param id_medio: The id_medio of this Reserva.
        :type id_medio: int
        """
        self.swagger_types = {
            'id_reserva': int,
            'titulae_reserva': str,
            'hora_inicio': str,
            'hora_fin': str,
            'fecha_reserva': str,
            'id_medio': int
        }

        self.attribute_map = {
            'id_reserva': 'id_reserva',
            'titulae_reserva': 'titulaeReserva',
            'hora_inicio': 'horaInicio',
            'hora_fin': 'horaFin',
            'fecha_reserva': 'fechaReserva',
            'id_medio': 'idMedio'
        }

        self._id_reserva = id_reserva
        self._titulae_reserva = titulae_reserva
        self._hora_inicio = hora_inicio
        self._hora_fin = hora_fin
        self._fecha_reserva = fecha_reserva
        self._id_medio = id_medio

    @classmethod
    def from_dict(cls, dikt) -> 'Reserva':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reserva of this Reserva.
        :rtype: Reserva
        """
        return deserialize_model(dikt, cls)

    @property
    def id_reserva(self) -> int:
        """
        Gets the id_reserva of this Reserva.

        :return: The id_reserva of this Reserva.
        :rtype: int
        """
        return self._id_reserva

    @id_reserva.setter
    def id_reserva(self, id_reserva: int):
        """
        Sets the id_reserva of this Reserva.

        :param id_reserva: The id_reserva of this Reserva.
        :type id_reserva: int
        """

        self._id_reserva = id_reserva

    @property
    def titulae_reserva(self) -> str:
        """
        Gets the titulae_reserva of this Reserva.

        :return: The titulae_reserva of this Reserva.
        :rtype: str
        """
        return self._titulae_reserva

    @titulae_reserva.setter
    def titulae_reserva(self, titulae_reserva: str):
        """
        Sets the titulae_reserva of this Reserva.

        :param titulae_reserva: The titulae_reserva of this Reserva.
        :type titulae_reserva: str
        """

        self._titulae_reserva = titulae_reserva

    @property
    def hora_inicio(self) -> str:
        """
        Gets the hora_inicio of this Reserva.

        :return: The hora_inicio of this Reserva.
        :rtype: str
        """
        return self._hora_inicio

    @hora_inicio.setter
    def hora_inicio(self, hora_inicio: str):
        """
        Sets the hora_inicio of this Reserva.

        :param hora_inicio: The hora_inicio of this Reserva.
        :type hora_inicio: str
        """

        self._hora_inicio = hora_inicio

    @property
    def hora_fin(self) -> str:
        """
        Gets the hora_fin of this Reserva.

        :return: The hora_fin of this Reserva.
        :rtype: str
        """
        return self._hora_fin

    @hora_fin.setter
    def hora_fin(self, hora_fin: str):
        """
        Sets the hora_fin of this Reserva.

        :param hora_fin: The hora_fin of this Reserva.
        :type hora_fin: str
        """

        self._hora_fin = hora_fin

    @property
    def fecha_reserva(self) -> str:
        """
        Gets the fecha_reserva of this Reserva.

        :return: The fecha_reserva of this Reserva.
        :rtype: str
        """
        return self._fecha_reserva

    @fecha_reserva.setter
    def fecha_reserva(self, fecha_reserva: str):
        """
        Sets the fecha_reserva of this Reserva.

        :param fecha_reserva: The fecha_reserva of this Reserva.
        :type fecha_reserva: str
        """

        self._fecha_reserva = fecha_reserva

    @property
    def id_medio(self) -> int:
        """
        Gets the id_medio of this Reserva.

        :return: The id_medio of this Reserva.
        :rtype: int
        """
        return self._id_medio

    @id_medio.setter
    def id_medio(self, id_medio: int):
        """
        Sets the id_medio of this Reserva.

        :param id_medio: The id_medio of this Reserva.
        :type id_medio: int
        """

        self._id_medio = id_medio

