# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Creditos(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, creditos: int=None, asignatura: str=None):
        """
        Creditos - a model defined in Swagger

        :param creditos: The creditos of this Creditos.
        :type creditos: int
        :param asignatura: The asignatura of this Creditos.
        :type asignatura: str
        """
        self.swagger_types = {
            'creditos': int,
            'asignatura': str
        }

        self.attribute_map = {
            'creditos': 'creditos',
            'asignatura': 'asignatura'
        }

        self._creditos = creditos
        self._asignatura = asignatura

    @classmethod
    def from_dict(cls, dikt) -> 'Creditos':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Creditos of this Creditos.
        :rtype: Creditos
        """
        return deserialize_model(dikt, cls)

    @property
    def creditos(self) -> int:
        """
        Gets the creditos of this Creditos.

        :return: The creditos of this Creditos.
        :rtype: int
        """
        return self._creditos

    @creditos.setter
    def creditos(self, creditos: int):
        """
        Sets the creditos of this Creditos.

        :param creditos: The creditos of this Creditos.
        :type creditos: int
        """

        self._creditos = creditos

    @property
    def asignatura(self) -> str:
        """
        Gets the asignatura of this Creditos.

        :return: The asignatura of this Creditos.
        :rtype: str
        """
        return self._asignatura

    @asignatura.setter
    def asignatura(self, asignatura: str):
        """
        Sets the asignatura of this Creditos.

        :param asignatura: The asignatura of this Creditos.
        :type asignatura: str
        """

        self._asignatura = asignatura

