# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DepartamentoPas(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_departamento: int=None, nombre: str=None, descripcion: str=None, id_facultad: int=None):
        """
        DepartamentoPas - a model defined in Swagger

        :param id_departamento: The id_departamento of this DepartamentoPas.
        :type id_departamento: int
        :param nombre: The nombre of this DepartamentoPas.
        :type nombre: str
        :param descripcion: The descripcion of this DepartamentoPas.
        :type descripcion: str
        :param id_facultad: The id_facultad of this DepartamentoPas.
        :type id_facultad: int
        """
        self.swagger_types = {
            'id_departamento': int,
            'nombre': str,
            'descripcion': str,
            'id_facultad': int
        }

        self.attribute_map = {
            'id_departamento': 'idDepartamento',
            'nombre': 'nombre',
            'descripcion': 'descripcion',
            'id_facultad': 'idFacultad'
        }

        self._id_departamento = id_departamento
        self._nombre = nombre
        self._descripcion = descripcion
        self._id_facultad = id_facultad

    @classmethod
    def from_dict(cls, dikt) -> 'DepartamentoPas':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DepartamentoPas of this DepartamentoPas.
        :rtype: DepartamentoPas
        """
        return deserialize_model(dikt, cls)

    @property
    def id_departamento(self) -> int:
        """
        Gets the id_departamento of this DepartamentoPas.

        :return: The id_departamento of this DepartamentoPas.
        :rtype: int
        """
        return self._id_departamento

    @id_departamento.setter
    def id_departamento(self, id_departamento: int):
        """
        Sets the id_departamento of this DepartamentoPas.

        :param id_departamento: The id_departamento of this DepartamentoPas.
        :type id_departamento: int
        """

        self._id_departamento = id_departamento

    @property
    def nombre(self) -> str:
        """
        Gets the nombre of this DepartamentoPas.

        :return: The nombre of this DepartamentoPas.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """
        Sets the nombre of this DepartamentoPas.

        :param nombre: The nombre of this DepartamentoPas.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def descripcion(self) -> str:
        """
        Gets the descripcion of this DepartamentoPas.

        :return: The descripcion of this DepartamentoPas.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """
        Sets the descripcion of this DepartamentoPas.

        :param descripcion: The descripcion of this DepartamentoPas.
        :type descripcion: str
        """

        self._descripcion = descripcion

    @property
    def id_facultad(self) -> int:
        """
        Gets the id_facultad of this DepartamentoPas.

        :return: The id_facultad of this DepartamentoPas.
        :rtype: int
        """
        return self._id_facultad

    @id_facultad.setter
    def id_facultad(self, id_facultad: int):
        """
        Sets the id_facultad of this DepartamentoPas.

        :param id_facultad: The id_facultad of this DepartamentoPas.
        :type id_facultad: int
        """

        self._id_facultad = id_facultad

