# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Pas(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_pas: int=None, categoria: str=None, puesto: str=None, dni: str=None, nombre: str=None, apellidos: str=None, fecha_incorporacion: str=None, direccion: str=None, telefono: str=None, id_departamento: int=None):
        """
        Pas - a model defined in Swagger

        :param id_pas: The id_pas of this Pas.
        :type id_pas: int
        :param categoria: The categoria of this Pas.
        :type categoria: str
        :param puesto: The puesto of this Pas.
        :type puesto: str
        :param dni: The dni of this Pas.
        :type dni: str
        :param nombre: The nombre of this Pas.
        :type nombre: str
        :param apellidos: The apellidos of this Pas.
        :type apellidos: str
        :param fecha_incorporacion: The fecha_incorporacion of this Pas.
        :type fecha_incorporacion: str
        :param direccion: The direccion of this Pas.
        :type direccion: str
        :param telefono: The telefono of this Pas.
        :type telefono: str
        :param id_departamento: The id_departamento of this Pas.
        :type id_departamento: int
        """
        self.swagger_types = {
            'id_pas': int,
            'categoria': str,
            'puesto': str,
            'dni': str,
            'nombre': str,
            'apellidos': str,
            'fecha_incorporacion': str,
            'direccion': str,
            'telefono': str,
            'id_departamento': int
        }

        self.attribute_map = {
            'id_pas': 'idPas',
            'categoria': 'categoria',
            'puesto': 'puesto',
            'dni': 'dni',
            'nombre': 'nombre',
            'apellidos': 'apellidos',
            'fecha_incorporacion': 'fechaIncorporacion',
            'direccion': 'direccion',
            'telefono': 'telefono',
            'id_departamento': 'idDepartamento'
        }

        self._id_pas = id_pas
        self._categoria = categoria
        self._puesto = puesto
        self._dni = dni
        self._nombre = nombre
        self._apellidos = apellidos
        self._fecha_incorporacion = fecha_incorporacion
        self._direccion = direccion
        self._telefono = telefono
        self._id_departamento = id_departamento

    @classmethod
    def from_dict(cls, dikt) -> 'Pas':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pas of this Pas.
        :rtype: Pas
        """
        return deserialize_model(dikt, cls)

    @property
    def id_pas(self) -> int:
        """
        Gets the id_pas of this Pas.

        :return: The id_pas of this Pas.
        :rtype: int
        """
        return self._id_pas

    @id_pas.setter
    def id_pas(self, id_pas: int):
        """
        Sets the id_pas of this Pas.

        :param id_pas: The id_pas of this Pas.
        :type id_pas: int
        """

        self._id_pas = id_pas

    @property
    def categoria(self) -> str:
        """
        Gets the categoria of this Pas.

        :return: The categoria of this Pas.
        :rtype: str
        """
        return self._categoria

    @categoria.setter
    def categoria(self, categoria: str):
        """
        Sets the categoria of this Pas.

        :param categoria: The categoria of this Pas.
        :type categoria: str
        """

        self._categoria = categoria

    @property
    def puesto(self) -> str:
        """
        Gets the puesto of this Pas.

        :return: The puesto of this Pas.
        :rtype: str
        """
        return self._puesto

    @puesto.setter
    def puesto(self, puesto: str):
        """
        Sets the puesto of this Pas.

        :param puesto: The puesto of this Pas.
        :type puesto: str
        """

        self._puesto = puesto

    @property
    def dni(self) -> str:
        """
        Gets the dni of this Pas.

        :return: The dni of this Pas.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """
        Sets the dni of this Pas.

        :param dni: The dni of this Pas.
        :type dni: str
        """

        self._dni = dni

    @property
    def nombre(self) -> str:
        """
        Gets the nombre of this Pas.

        :return: The nombre of this Pas.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """
        Sets the nombre of this Pas.

        :param nombre: The nombre of this Pas.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def apellidos(self) -> str:
        """
        Gets the apellidos of this Pas.

        :return: The apellidos of this Pas.
        :rtype: str
        """
        return self._apellidos

    @apellidos.setter
    def apellidos(self, apellidos: str):
        """
        Sets the apellidos of this Pas.

        :param apellidos: The apellidos of this Pas.
        :type apellidos: str
        """

        self._apellidos = apellidos

    @property
    def fecha_incorporacion(self) -> str:
        """
        Gets the fecha_incorporacion of this Pas.

        :return: The fecha_incorporacion of this Pas.
        :rtype: str
        """
        return self._fecha_incorporacion

    @fecha_incorporacion.setter
    def fecha_incorporacion(self, fecha_incorporacion: str):
        """
        Sets the fecha_incorporacion of this Pas.

        :param fecha_incorporacion: The fecha_incorporacion of this Pas.
        :type fecha_incorporacion: str
        """

        self._fecha_incorporacion = fecha_incorporacion

    @property
    def direccion(self) -> str:
        """
        Gets the direccion of this Pas.

        :return: The direccion of this Pas.
        :rtype: str
        """
        return self._direccion

    @direccion.setter
    def direccion(self, direccion: str):
        """
        Sets the direccion of this Pas.

        :param direccion: The direccion of this Pas.
        :type direccion: str
        """

        self._direccion = direccion

    @property
    def telefono(self) -> str:
        """
        Gets the telefono of this Pas.

        :return: The telefono of this Pas.
        :rtype: str
        """
        return self._telefono

    @telefono.setter
    def telefono(self, telefono: str):
        """
        Sets the telefono of this Pas.

        :param telefono: The telefono of this Pas.
        :type telefono: str
        """

        self._telefono = telefono

    @property
    def id_departamento(self) -> int:
        """
        Gets the id_departamento of this Pas.

        :return: The id_departamento of this Pas.
        :rtype: int
        """
        return self._id_departamento

    @id_departamento.setter
    def id_departamento(self, id_departamento: int):
        """
        Sets the id_departamento of this Pas.

        :param id_departamento: The id_departamento of this Pas.
        :type id_departamento: int
        """

        self._id_departamento = id_departamento

