# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Grado(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, cod_grado: int=None, nombre: str=None, id_universidad: int=None, num_cred_obligatorios: int=None, num_cred_transversales: int=None, num_cread_optativos: int=None):
        """
        Grado - a model defined in Swagger

        :param cod_grado: The cod_grado of this Grado.
        :type cod_grado: int
        :param nombre: The nombre of this Grado.
        :type nombre: str
        :param id_universidad: The id_universidad of this Grado.
        :type id_universidad: int
        :param num_cred_obligatorios: The num_cred_obligatorios of this Grado.
        :type num_cred_obligatorios: int
        :param num_cred_transversales: The num_cred_transversales of this Grado.
        :type num_cred_transversales: int
        :param num_cread_optativos: The num_cread_optativos of this Grado.
        :type num_cread_optativos: int
        """
        self.swagger_types = {
            'cod_grado': int,
            'nombre': str,
            'id_universidad': int,
            'num_cred_obligatorios': int,
            'num_cred_transversales': int,
            'num_cread_optativos': int
        }

        self.attribute_map = {
            'cod_grado': 'codGrado',
            'nombre': 'nombre',
            'id_universidad': 'idUniversidad',
            'num_cred_obligatorios': 'numCredObligatorios',
            'num_cred_transversales': 'numCredTransversales',
            'num_cread_optativos': 'numCreadOptativos'
        }

        self._cod_grado = cod_grado
        self._nombre = nombre
        self._id_universidad = id_universidad
        self._num_cred_obligatorios = num_cred_obligatorios
        self._num_cred_transversales = num_cred_transversales
        self._num_cread_optativos = num_cread_optativos

    @classmethod
    def from_dict(cls, dikt) -> 'Grado':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Grado of this Grado.
        :rtype: Grado
        """
        return deserialize_model(dikt, cls)

    @property
    def cod_grado(self) -> int:
        """
        Gets the cod_grado of this Grado.

        :return: The cod_grado of this Grado.
        :rtype: int
        """
        return self._cod_grado

    @cod_grado.setter
    def cod_grado(self, cod_grado: int):
        """
        Sets the cod_grado of this Grado.

        :param cod_grado: The cod_grado of this Grado.
        :type cod_grado: int
        """

        self._cod_grado = cod_grado

    @property
    def nombre(self) -> str:
        """
        Gets the nombre of this Grado.

        :return: The nombre of this Grado.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """
        Sets the nombre of this Grado.

        :param nombre: The nombre of this Grado.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def id_universidad(self) -> int:
        """
        Gets the id_universidad of this Grado.

        :return: The id_universidad of this Grado.
        :rtype: int
        """
        return self._id_universidad

    @id_universidad.setter
    def id_universidad(self, id_universidad: int):
        """
        Sets the id_universidad of this Grado.

        :param id_universidad: The id_universidad of this Grado.
        :type id_universidad: int
        """

        self._id_universidad = id_universidad

    @property
    def num_cred_obligatorios(self) -> int:
        """
        Gets the num_cred_obligatorios of this Grado.

        :return: The num_cred_obligatorios of this Grado.
        :rtype: int
        """
        return self._num_cred_obligatorios

    @num_cred_obligatorios.setter
    def num_cred_obligatorios(self, num_cred_obligatorios: int):
        """
        Sets the num_cred_obligatorios of this Grado.

        :param num_cred_obligatorios: The num_cred_obligatorios of this Grado.
        :type num_cred_obligatorios: int
        """

        self._num_cred_obligatorios = num_cred_obligatorios

    @property
    def num_cred_transversales(self) -> int:
        """
        Gets the num_cred_transversales of this Grado.

        :return: The num_cred_transversales of this Grado.
        :rtype: int
        """
        return self._num_cred_transversales

    @num_cred_transversales.setter
    def num_cred_transversales(self, num_cred_transversales: int):
        """
        Sets the num_cred_transversales of this Grado.

        :param num_cred_transversales: The num_cred_transversales of this Grado.
        :type num_cred_transversales: int
        """

        self._num_cred_transversales = num_cred_transversales

    @property
    def num_cread_optativos(self) -> int:
        """
        Gets the num_cread_optativos of this Grado.

        :return: The num_cread_optativos of this Grado.
        :rtype: int
        """
        return self._num_cread_optativos

    @num_cread_optativos.setter
    def num_cread_optativos(self, num_cread_optativos: int):
        """
        Sets the num_cread_optativos of this Grado.

        :param num_cread_optativos: The num_cread_optativos of this Grado.
        :type num_cread_optativos: int
        """

        self._num_cread_optativos = num_cread_optativos

