# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class MedioFisicoCentro(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_medio: int=None, nombre_medio: str=None, tipo_medio: str=None, precio_medio: float=None, capacidad: int=None, id_centro: int=None):
        """
        MedioFisicoCentro - a model defined in Swagger

        :param id_medio: The id_medio of this MedioFisicoCentro.
        :type id_medio: int
        :param nombre_medio: The nombre_medio of this MedioFisicoCentro.
        :type nombre_medio: str
        :param tipo_medio: The tipo_medio of this MedioFisicoCentro.
        :type tipo_medio: str
        :param precio_medio: The precio_medio of this MedioFisicoCentro.
        :type precio_medio: float
        :param capacidad: The capacidad of this MedioFisicoCentro.
        :type capacidad: int
        :param id_centro: The id_centro of this MedioFisicoCentro.
        :type id_centro: int
        """
        self.swagger_types = {
            'id_medio': int,
            'nombre_medio': str,
            'tipo_medio': str,
            'precio_medio': float,
            'capacidad': int,
            'id_centro': int
        }

        self.attribute_map = {
            'id_medio': 'idMedio',
            'nombre_medio': 'nombreMedio',
            'tipo_medio': 'tipoMedio',
            'precio_medio': 'precioMedio',
            'capacidad': 'capacidad',
            'id_centro': 'idCentro'
        }

        self._id_medio = id_medio
        self._nombre_medio = nombre_medio
        self._tipo_medio = tipo_medio
        self._precio_medio = precio_medio
        self._capacidad = capacidad
        self._id_centro = id_centro

    @classmethod
    def from_dict(cls, dikt) -> 'MedioFisicoCentro':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MedioFisicoCentro of this MedioFisicoCentro.
        :rtype: MedioFisicoCentro
        """
        return deserialize_model(dikt, cls)

    @property
    def id_medio(self) -> int:
        """
        Gets the id_medio of this MedioFisicoCentro.

        :return: The id_medio of this MedioFisicoCentro.
        :rtype: int
        """
        return self._id_medio

    @id_medio.setter
    def id_medio(self, id_medio: int):
        """
        Sets the id_medio of this MedioFisicoCentro.

        :param id_medio: The id_medio of this MedioFisicoCentro.
        :type id_medio: int
        """

        self._id_medio = id_medio

    @property
    def nombre_medio(self) -> str:
        """
        Gets the nombre_medio of this MedioFisicoCentro.

        :return: The nombre_medio of this MedioFisicoCentro.
        :rtype: str
        """
        return self._nombre_medio

    @nombre_medio.setter
    def nombre_medio(self, nombre_medio: str):
        """
        Sets the nombre_medio of this MedioFisicoCentro.

        :param nombre_medio: The nombre_medio of this MedioFisicoCentro.
        :type nombre_medio: str
        """

        self._nombre_medio = nombre_medio

    @property
    def tipo_medio(self) -> str:
        """
        Gets the tipo_medio of this MedioFisicoCentro.

        :return: The tipo_medio of this MedioFisicoCentro.
        :rtype: str
        """
        return self._tipo_medio

    @tipo_medio.setter
    def tipo_medio(self, tipo_medio: str):
        """
        Sets the tipo_medio of this MedioFisicoCentro.

        :param tipo_medio: The tipo_medio of this MedioFisicoCentro.
        :type tipo_medio: str
        """

        self._tipo_medio = tipo_medio

    @property
    def precio_medio(self) -> float:
        """
        Gets the precio_medio of this MedioFisicoCentro.

        :return: The precio_medio of this MedioFisicoCentro.
        :rtype: float
        """
        return self._precio_medio

    @precio_medio.setter
    def precio_medio(self, precio_medio: float):
        """
        Sets the precio_medio of this MedioFisicoCentro.

        :param precio_medio: The precio_medio of this MedioFisicoCentro.
        :type precio_medio: float
        """

        self._precio_medio = precio_medio

    @property
    def capacidad(self) -> int:
        """
        Gets the capacidad of this MedioFisicoCentro.

        :return: The capacidad of this MedioFisicoCentro.
        :rtype: int
        """
        return self._capacidad

    @capacidad.setter
    def capacidad(self, capacidad: int):
        """
        Sets the capacidad of this MedioFisicoCentro.

        :param capacidad: The capacidad of this MedioFisicoCentro.
        :type capacidad: int
        """

        self._capacidad = capacidad

    @property
    def id_centro(self) -> int:
        """
        Gets the id_centro of this MedioFisicoCentro.

        :return: The id_centro of this MedioFisicoCentro.
        :rtype: int
        """
        return self._id_centro

    @id_centro.setter
    def id_centro(self, id_centro: int):
        """
        Sets the id_centro of this MedioFisicoCentro.

        :param id_centro: The id_centro of this MedioFisicoCentro.
        :type id_centro: int
        """

        self._id_centro = id_centro

