# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Universidad(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, dir: str=None, cod_uni: int=None):
        """
        Universidad - a model defined in Swagger

        :param name: The name of this Universidad.
        :type name: str
        :param dir: The dir of this Universidad.
        :type dir: str
        :param cod_uni: The cod_uni of this Universidad.
        :type cod_uni: int
        """
        self.swagger_types = {
            'name': str,
            'dir': str,
            'cod_uni': int
        }

        self.attribute_map = {
            'name': 'Name',
            'dir': 'Dir',
            'cod_uni': 'codUni'
        }

        self._name = name
        self._dir = dir
        self._cod_uni = cod_uni

    @classmethod
    def from_dict(cls, dikt) -> 'Universidad':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Universidad of this Universidad.
        :rtype: Universidad
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this Universidad.

        :return: The name of this Universidad.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Universidad.

        :param name: The name of this Universidad.
        :type name: str
        """

        self._name = name

    @property
    def dir(self) -> str:
        """
        Gets the dir of this Universidad.

        :return: The dir of this Universidad.
        :rtype: str
        """
        return self._dir

    @dir.setter
    def dir(self, dir: str):
        """
        Sets the dir of this Universidad.

        :param dir: The dir of this Universidad.
        :type dir: str
        """

        self._dir = dir

    @property
    def cod_uni(self) -> int:
        """
        Gets the cod_uni of this Universidad.

        :return: The cod_uni of this Universidad.
        :rtype: int
        """
        return self._cod_uni

    @cod_uni.setter
    def cod_uni(self, cod_uni: int):
        """
        Sets the cod_uni of this Universidad.

        :param cod_uni: The cod_uni of this Universidad.
        :type cod_uni: int
        """

        self._cod_uni = cod_uni

