swagger: '2.0'
info:
  description: >-
    API sencilla para aprender a crear APIs REST con OpenAPI documents en
    SWAGGER y a implementarlos con Python-Flask
  version: 1.0.0
  title: API sencilla para la gestión de universidades
host: 'localhost:8080'
basePath: /miAplicacion
tags:
  - name: Universidades
    description: Operaciones sobre las universidades
schemes:
  - https
paths:
  /universidad:
    get:
      tags:
        - Universidades
      summary: Obtiene universidades
      description: Obtiene un listado de las universidades del sistema.
      operationId: obtener_universidad
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tamanoPagina
          in: query
          description: Número de univesidades devueltas
          required: true
          type: integer
        - name: numeroPaginas
          in: query
          description: Número de páginas devueltas
          required: true
          type: integer
      responses:
        '200':
          description: Una lista de universidades
          schema:
            type: array
            items:
              $ref: '#/definitions/Universidad'
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
    post:
      tags:
        - Universidades
      summary: Crea una universidad
      description: Añade una universidad a la lista de universidades.
      operationId: crear_universidad
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: universidad
          description: La universidad que se va a añadir.
          required: true
          schema:
            $ref: '#/definitions/Universidad'
      responses:
        '200':
          description: Universidad creada correctamente.
        '400':
          description: La universidad no ha podido ser creado.
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
  '/universidad/{codUni}':
    get:
      tags:
        - Universidades
      summary: Devuelve una universidad a partir de su código
      description: Devuelve una única universidad identificada por su codigo de universidad
      operationId: universidad_getUni
      parameters:
        - name: codUni
          in: path
          description: Codigo de la universidad
          required: true
          type: integer
      responses:
        '200':
          description: Operación correcta
          schema:
            $ref: '#/definitions/Universidad'
        '404':
          description: La universidad no existe.
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
  /grado:
    get:
      tags:
        - Grados
      summary: Obtiene una lista de todos los grados del sistema.
      description: Obtiene un listado de los grados del sistema.
      operationId: getGrados
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tamanoPagina
          in: query
          description: Número de grados devueltas
          required: true
          type: integer
        - name: numeroPaginas
          in: query
          description: Número de páginas devueltas
          required: true
          type: integer
      responses:
        '200':
          description: Una lista de grados
          schema:
            type: array
            items:
              $ref: '#/definitions/Universidad'
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
    post:
      tags:
        - Grados
      description: Añade un grado a nuestra base de datos
      summary: Añade un grado a la base de datos.
      operationId: postGrado
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: grado
          description: El grado  que se va a añadir.
          required: true
          schema:
            $ref: '#/definitions/Grado'
      responses:
        '200':
          description: Grado creado correctamente.
        '404':
          description: El grado no ha podido ser creado.
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
  '/grado/{codGrado}':
    get:
      tags:
        - Grados
      summary: Obtienes un grado a partir de su código
      description: >-
        Devuelve un objeto del tipo grado con todos sus datos, a partir del
        código del grado.
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: codGrado
          in: path
          description: Codigo del grado
          required: true
          type: integer
      responses:
        '200':
          description: Grado devuelto correctamente
          schema:
            $ref: '#/definitions/Grado'
        '404':
          description: Ha habido un problema al obtener el grado
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
  /asignatura:
    get:
      tags:
        - Asignaturas
      summary: Obtiene un listado de todas las asignaturas de la Base de datos
      description: Devuelve una lista con las asignaturas.
      operationId: getAsignaturas
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tamanoPagina
          in: query
          description: Número de grados devueltos
          required: true
          type: integer
        - name: numeroPaginas
          in: query
          description: Número de páginas devueltos
          required: true
          type: integer
      responses:
        '200':
          description: Una lista de asignaturas
          schema:
            type: array
            items:
              $ref: '#/definitions/Asignatura'
        '404':
          description: No se ha podido devovler las asignaturas
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
    post:
      tags:
        - Asignaturas
      summary: Añadir una asignatura a nuestra Base de datos.
      description: Añade una asignatura a nuestra base de datos.
      operationId: postAsignatura
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: asignatura
          description: La asignatura que se va a añadir.
          required: true
          schema:
            $ref: '#/definitions/Asignatura'
      responses:
        '200':
          description: La asignatura se ha creado de manera correcta.
        '404':
          description: No se ha podido introducir la asignatura.
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
  '/asignatura/{idAsignatura}':
    get:
      tags:
        - Asignaturas
      summary: Obtienes una asignatura a partir de su código
      description: >-
        Devuelve un objeto del tipo asignatura con todos sus datos, a partir del
        código del grado.
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: idAsignatura
          in: path
          description: Codigo de la asignatura
          required: true
          type: integer
      responses:
        '200':
          description: Asignatura devuelta correctamente
          schema:
            $ref: '#/definitions/Asignatura'
        '404':
          description: Ha habido un problema al obtener el grado
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
  /medioFisico:
    get:
      tags:
        - Medio Físicos
      summary: Obtiene una lista de todos los medios físicos del sistema.
      description: Obtiene un listado de los medios físicos  del sistema.
      operationId: getMedioF
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tamanoPagina
          in: query
          description: Número de medios devueltos
          required: true
          type: integer
        - name: numeroPaginas
          in: query
          description: Número de páginas devueltas
          required: true
          type: integer
      responses:
        '200':
          description: Una lista de medios físicos
          schema:
            type: array
            items:
              $ref: '#/definitions/MedioFisico'
        '404':
          description: No ha sido posible devolver la lista de medios.
      x-swagger-router-controller: swagger_server.controllers.usuarios_controller
  '/medioFisico/{idMedio}':
    get:
      tags:
        - Medio Físicos
      summary: Obtienes un medio a partir de su código
      description: >-
        Devuelve un objeto del tipo medio con todos sus datos, a partir del
        código del grado.
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: idMedio
          in: path
          description: Codigo del medio
          required: true
          type: integer
      responses:
        '200':
          description: Medio devuelto correctamente
          schema:
            $ref: '#/definitions/MedioFisico'
        '404':
          description: Ha habido un problema al obtener el grado
definitions:
  Universidad:
    type: object
    properties:
      Name:
        type: string
      Dir:
        type: string
      codUni:
        type: integer
  Grado:
    type: object
    properties:
      codGrado:
        type: integer
      nombre:
        type: string
      idUniversidad:
        type: integer
      numCredObligatorios:
        type: integer
      numCredTransversales:
        type: integer
      numCreadOptativos:
        type: integer
  Asignatura:
    type: object
    properties:
      idAsignatura:
        type: integer
      nombre:
        type: string
  MedioFisico:
    type: object
    properties:
      idMedio:
        type: integer
      nombre:
        type: string
      tipo:
        type: string
      precio_hora:
        type: number
      capacidad:
        type: integer
      codUni:
        type: integer
