# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class MatriculaAsignatura(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_matricula: int=None, id_grado_asignatura: int=None, nota: float=None):
        """
        MatriculaAsignatura - a model defined in Swagger

        :param id_matricula: The id_matricula of this MatriculaAsignatura.
        :type id_matricula: int
        :param id_grado_asignatura: The id_grado_asignatura of this MatriculaAsignatura.
        :type id_grado_asignatura: int
        :param nota: The nota of this MatriculaAsignatura.
        :type nota: float
        """
        self.swagger_types = {
            'id_matricula': int,
            'id_grado_asignatura': int,
            'nota': float
        }

        self.attribute_map = {
            'id_matricula': 'idMatricula',
            'id_grado_asignatura': 'idGradoAsignatura',
            'nota': 'nota'
        }

        self._id_matricula = id_matricula
        self._id_grado_asignatura = id_grado_asignatura
        self._nota = nota

    @classmethod
    def from_dict(cls, dikt) -> 'MatriculaAsignatura':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Matricula_asignatura of this MatriculaAsignatura.
        :rtype: MatriculaAsignatura
        """
        return deserialize_model(dikt, cls)

    @property
    def id_matricula(self) -> int:
        """
        Gets the id_matricula of this MatriculaAsignatura.

        :return: The id_matricula of this MatriculaAsignatura.
        :rtype: int
        """
        return self._id_matricula

    @id_matricula.setter
    def id_matricula(self, id_matricula: int):
        """
        Sets the id_matricula of this MatriculaAsignatura.

        :param id_matricula: The id_matricula of this MatriculaAsignatura.
        :type id_matricula: int
        """

        self._id_matricula = id_matricula

    @property
    def id_grado_asignatura(self) -> int:
        """
        Gets the id_grado_asignatura of this MatriculaAsignatura.

        :return: The id_grado_asignatura of this MatriculaAsignatura.
        :rtype: int
        """
        return self._id_grado_asignatura

    @id_grado_asignatura.setter
    def id_grado_asignatura(self, id_grado_asignatura: int):
        """
        Sets the id_grado_asignatura of this MatriculaAsignatura.

        :param id_grado_asignatura: The id_grado_asignatura of this MatriculaAsignatura.
        :type id_grado_asignatura: int
        """

        self._id_grado_asignatura = id_grado_asignatura

    @property
    def nota(self) -> float:
        """
        Gets the nota of this MatriculaAsignatura.

        :return: The nota of this MatriculaAsignatura.
        :rtype: float
        """
        return self._nota

    @nota.setter
    def nota(self, nota: float):
        """
        Sets the nota of this MatriculaAsignatura.

        :param nota: The nota of this MatriculaAsignatura.
        :type nota: float
        """

        self._nota = nota

