# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Alumno(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_pago_matricula_alumno: int=None, importe_matricula_alumno: int=None, pago_matricula_alumno_realizado: bool=None, id_departamento_contable: int=None, id_alumno: int=None):
        """
        Alumno - a model defined in Swagger

        :param id_pago_matricula_alumno: The id_pago_matricula_alumno of this Alumno.
        :type id_pago_matricula_alumno: int
        :param importe_matricula_alumno: The importe_matricula_alumno of this Alumno.
        :type importe_matricula_alumno: int
        :param pago_matricula_alumno_realizado: The pago_matricula_alumno_realizado of this Alumno.
        :type pago_matricula_alumno_realizado: bool
        :param id_departamento_contable: The id_departamento_contable of this Alumno.
        :type id_departamento_contable: int
        :param id_alumno: The id_alumno of this Alumno.
        :type id_alumno: int
        """
        self.swagger_types = {
            'id_pago_matricula_alumno': int,
            'importe_matricula_alumno': int,
            'pago_matricula_alumno_realizado': bool,
            'id_departamento_contable': int,
            'id_alumno': int
        }

        self.attribute_map = {
            'id_pago_matricula_alumno': 'id_PagoMatriculaAlumno',
            'importe_matricula_alumno': 'importeMatriculaAlumno',
            'pago_matricula_alumno_realizado': 'pagoMatriculaAlumnoRealizado',
            'id_departamento_contable': 'id_departamentoContable',
            'id_alumno': 'id_alumno'
        }

        self._id_pago_matricula_alumno = id_pago_matricula_alumno
        self._importe_matricula_alumno = importe_matricula_alumno
        self._pago_matricula_alumno_realizado = pago_matricula_alumno_realizado
        self._id_departamento_contable = id_departamento_contable
        self._id_alumno = id_alumno

    @classmethod
    def from_dict(cls, dikt) -> 'Alumno':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Alumno of this Alumno.
        :rtype: Alumno
        """
        return deserialize_model(dikt, cls)

    @property
    def id_pago_matricula_alumno(self) -> int:
        """
        Gets the id_pago_matricula_alumno of this Alumno.

        :return: The id_pago_matricula_alumno of this Alumno.
        :rtype: int
        """
        return self._id_pago_matricula_alumno

    @id_pago_matricula_alumno.setter
    def id_pago_matricula_alumno(self, id_pago_matricula_alumno: int):
        """
        Sets the id_pago_matricula_alumno of this Alumno.

        :param id_pago_matricula_alumno: The id_pago_matricula_alumno of this Alumno.
        :type id_pago_matricula_alumno: int
        """

        self._id_pago_matricula_alumno = id_pago_matricula_alumno

    @property
    def importe_matricula_alumno(self) -> int:
        """
        Gets the importe_matricula_alumno of this Alumno.

        :return: The importe_matricula_alumno of this Alumno.
        :rtype: int
        """
        return self._importe_matricula_alumno

    @importe_matricula_alumno.setter
    def importe_matricula_alumno(self, importe_matricula_alumno: int):
        """
        Sets the importe_matricula_alumno of this Alumno.

        :param importe_matricula_alumno: The importe_matricula_alumno of this Alumno.
        :type importe_matricula_alumno: int
        """

        self._importe_matricula_alumno = importe_matricula_alumno

    @property
    def pago_matricula_alumno_realizado(self) -> bool:
        """
        Gets the pago_matricula_alumno_realizado of this Alumno.

        :return: The pago_matricula_alumno_realizado of this Alumno.
        :rtype: bool
        """
        return self._pago_matricula_alumno_realizado

    @pago_matricula_alumno_realizado.setter
    def pago_matricula_alumno_realizado(self, pago_matricula_alumno_realizado: bool):
        """
        Sets the pago_matricula_alumno_realizado of this Alumno.

        :param pago_matricula_alumno_realizado: The pago_matricula_alumno_realizado of this Alumno.
        :type pago_matricula_alumno_realizado: bool
        """

        self._pago_matricula_alumno_realizado = pago_matricula_alumno_realizado

    @property
    def id_departamento_contable(self) -> int:
        """
        Gets the id_departamento_contable of this Alumno.

        :return: The id_departamento_contable of this Alumno.
        :rtype: int
        """
        return self._id_departamento_contable

    @id_departamento_contable.setter
    def id_departamento_contable(self, id_departamento_contable: int):
        """
        Sets the id_departamento_contable of this Alumno.

        :param id_departamento_contable: The id_departamento_contable of this Alumno.
        :type id_departamento_contable: int
        """

        self._id_departamento_contable = id_departamento_contable

    @property
    def id_alumno(self) -> int:
        """
        Gets the id_alumno of this Alumno.

        :return: The id_alumno of this Alumno.
        :rtype: int
        """
        return self._id_alumno

    @id_alumno.setter
    def id_alumno(self, id_alumno: int):
        """
        Sets the id_alumno of this Alumno.

        :param id_alumno: The id_alumno of this Alumno.
        :type id_alumno: int
        """

        self._id_alumno = id_alumno

