# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Contable(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_contable: int=None, puesto_contable: str=None, dni_contable: str=None, nombre_contable: str=None, apellidos_contable: str=None, fecha_incorporacion_contable: str=None, direccion_contable: str=None, telefono_contable: str=None, id_departamento_contable: int=None):
        """
        Contable - a model defined in Swagger

        :param id_contable: The id_contable of this Contable.
        :type id_contable: int
        :param puesto_contable: The puesto_contable of this Contable.
        :type puesto_contable: str
        :param dni_contable: The dni_contable of this Contable.
        :type dni_contable: str
        :param nombre_contable: The nombre_contable of this Contable.
        :type nombre_contable: str
        :param apellidos_contable: The apellidos_contable of this Contable.
        :type apellidos_contable: str
        :param fecha_incorporacion_contable: The fecha_incorporacion_contable of this Contable.
        :type fecha_incorporacion_contable: str
        :param direccion_contable: The direccion_contable of this Contable.
        :type direccion_contable: str
        :param telefono_contable: The telefono_contable of this Contable.
        :type telefono_contable: str
        :param id_departamento_contable: The id_departamento_contable of this Contable.
        :type id_departamento_contable: int
        """
        self.swagger_types = {
            'id_contable': int,
            'puesto_contable': str,
            'dni_contable': str,
            'nombre_contable': str,
            'apellidos_contable': str,
            'fecha_incorporacion_contable': str,
            'direccion_contable': str,
            'telefono_contable': str,
            'id_departamento_contable': int
        }

        self.attribute_map = {
            'id_contable': 'id_contable',
            'puesto_contable': 'puestoContable',
            'dni_contable': 'dniContable',
            'nombre_contable': 'nombreContable',
            'apellidos_contable': 'apellidosContable',
            'fecha_incorporacion_contable': 'fechaIncorporacionContable',
            'direccion_contable': 'direccionContable',
            'telefono_contable': 'telefonoContable',
            'id_departamento_contable': 'id_departamentoContable'
        }

        self._id_contable = id_contable
        self._puesto_contable = puesto_contable
        self._dni_contable = dni_contable
        self._nombre_contable = nombre_contable
        self._apellidos_contable = apellidos_contable
        self._fecha_incorporacion_contable = fecha_incorporacion_contable
        self._direccion_contable = direccion_contable
        self._telefono_contable = telefono_contable
        self._id_departamento_contable = id_departamento_contable

    @classmethod
    def from_dict(cls, dikt) -> 'Contable':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Contable of this Contable.
        :rtype: Contable
        """
        return deserialize_model(dikt, cls)

    @property
    def id_contable(self) -> int:
        """
        Gets the id_contable of this Contable.

        :return: The id_contable of this Contable.
        :rtype: int
        """
        return self._id_contable

    @id_contable.setter
    def id_contable(self, id_contable: int):
        """
        Sets the id_contable of this Contable.

        :param id_contable: The id_contable of this Contable.
        :type id_contable: int
        """

        self._id_contable = id_contable

    @property
    def puesto_contable(self) -> str:
        """
        Gets the puesto_contable of this Contable.

        :return: The puesto_contable of this Contable.
        :rtype: str
        """
        return self._puesto_contable

    @puesto_contable.setter
    def puesto_contable(self, puesto_contable: str):
        """
        Sets the puesto_contable of this Contable.

        :param puesto_contable: The puesto_contable of this Contable.
        :type puesto_contable: str
        """

        self._puesto_contable = puesto_contable

    @property
    def dni_contable(self) -> str:
        """
        Gets the dni_contable of this Contable.

        :return: The dni_contable of this Contable.
        :rtype: str
        """
        return self._dni_contable

    @dni_contable.setter
    def dni_contable(self, dni_contable: str):
        """
        Sets the dni_contable of this Contable.

        :param dni_contable: The dni_contable of this Contable.
        :type dni_contable: str
        """

        self._dni_contable = dni_contable

    @property
    def nombre_contable(self) -> str:
        """
        Gets the nombre_contable of this Contable.

        :return: The nombre_contable of this Contable.
        :rtype: str
        """
        return self._nombre_contable

    @nombre_contable.setter
    def nombre_contable(self, nombre_contable: str):
        """
        Sets the nombre_contable of this Contable.

        :param nombre_contable: The nombre_contable of this Contable.
        :type nombre_contable: str
        """

        self._nombre_contable = nombre_contable

    @property
    def apellidos_contable(self) -> str:
        """
        Gets the apellidos_contable of this Contable.

        :return: The apellidos_contable of this Contable.
        :rtype: str
        """
        return self._apellidos_contable

    @apellidos_contable.setter
    def apellidos_contable(self, apellidos_contable: str):
        """
        Sets the apellidos_contable of this Contable.

        :param apellidos_contable: The apellidos_contable of this Contable.
        :type apellidos_contable: str
        """

        self._apellidos_contable = apellidos_contable

    @property
    def fecha_incorporacion_contable(self) -> str:
        """
        Gets the fecha_incorporacion_contable of this Contable.

        :return: The fecha_incorporacion_contable of this Contable.
        :rtype: str
        """
        return self._fecha_incorporacion_contable

    @fecha_incorporacion_contable.setter
    def fecha_incorporacion_contable(self, fecha_incorporacion_contable: str):
        """
        Sets the fecha_incorporacion_contable of this Contable.

        :param fecha_incorporacion_contable: The fecha_incorporacion_contable of this Contable.
        :type fecha_incorporacion_contable: str
        """

        self._fecha_incorporacion_contable = fecha_incorporacion_contable

    @property
    def direccion_contable(self) -> str:
        """
        Gets the direccion_contable of this Contable.

        :return: The direccion_contable of this Contable.
        :rtype: str
        """
        return self._direccion_contable

    @direccion_contable.setter
    def direccion_contable(self, direccion_contable: str):
        """
        Sets the direccion_contable of this Contable.

        :param direccion_contable: The direccion_contable of this Contable.
        :type direccion_contable: str
        """

        self._direccion_contable = direccion_contable

    @property
    def telefono_contable(self) -> str:
        """
        Gets the telefono_contable of this Contable.

        :return: The telefono_contable of this Contable.
        :rtype: str
        """
        return self._telefono_contable

    @telefono_contable.setter
    def telefono_contable(self, telefono_contable: str):
        """
        Sets the telefono_contable of this Contable.

        :param telefono_contable: The telefono_contable of this Contable.
        :type telefono_contable: str
        """

        self._telefono_contable = telefono_contable

    @property
    def id_departamento_contable(self) -> int:
        """
        Gets the id_departamento_contable of this Contable.

        :return: The id_departamento_contable of this Contable.
        :rtype: int
        """
        return self._id_departamento_contable

    @id_departamento_contable.setter
    def id_departamento_contable(self, id_departamento_contable: int):
        """
        Sets the id_departamento_contable of this Contable.

        :param id_departamento_contable: The id_departamento_contable of this Contable.
        :type id_departamento_contable: int
        """

        self._id_departamento_contable = id_departamento_contable

