# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class IngresoAlumno(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_PagoMatriculaAlumno: int=None, fechaMatriculaAlumno: str=None, importeMatriculaAlumno: int=None, pagoMatriculaAlumnoRealizado: bool=None, id_departamentoContable: int=None, id_alumno: int=None):
        """
        Contable - a model defined in Swagger

        :param id_PagoMatriculaAlumno: The id_PagoMatriculaAlumno of this Ingreso.
        :type id_PagoMatriculaAlumno: int
        :param fechaMatriculaAlumno: The fechaMatriculaAlumno of this Ingreso.
        :type puesto_contable: str
        :param importeMatriculaAlumno: The importeMatriculaAlumno of this Ingreso.
        :type dni_contable: int
        :param pagoMatriculaAlumnoRealizado: The PagoMatriculaAlumnoRealizado of this Ingreso.
        :type nombre_contable: bool
        :param id_departamentoContable: The id_departamentoContable of this Ingreso.
        :type apellidos_contable: int
        :param id_alumno: The id_alumno of this Ingreso.
        :type fecha_incorporacion_contable: int
        """
        self.swagger_types = {
            'id_PagoMatriculaAlumno': int,
            'fechaMatriculaAlumno': str,
            'importeMatriculaAlumno': int,
            'pagoMatriculaAlumnoRealizado': bool,
            'id_departamentoContable': int,
            'id_alumno': int,
        }

        self.attribute_map = {
            'id_PagoMatriculaAlumno': 'id_PagoMatriculaAlumno',
            'fechaMatriculaAlumno': 'fechaMatriculaAlumno',
            'importeMatriculaAlumno': 'importeMatriculaAlumno',
            'pagoMatriculaAlumnoRealizado': 'pagoMatriculaAlumnoRealizado',
            'id_departamentoContable': 'id_departamentoContable',
            'id_alumno': 'id_alumno',
        }

        self._id_PagoMatriculaAlumno = id_PagoMatriculaAlumno
        self._fechaMatriculaAlumno = fechaMatriculaAlumno
        self._importeMatriculaAlumno = importeMatriculaAlumno
        self._pagoMatriculaAlumnoRealizado = pagoMatriculaAlumnoRealizado
        self._id_departamentoContable = id_departamentoContable
        self._id_alumno = id_alumno

    @classmethod
    def from_dict(cls, dikt) -> 'IngresoAlumno':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ingreso of this Ingreso.
        :rtype: Ingreso
        """
        return deserialize_model(dikt, cls)

    @property
    def id_PagoMatriculaAlumno(self) -> int:
        """
        Gets the id_contable of this Contable.

        :return: The id_PagoMatriculaAlumno of this Ingreso.
        :rtype: int
        """
        return self._id_PagoMatriculaAlumno

    @id_PagoMatriculaAlumno.setter
    def id_PagoMatriculaAlumno(self, id_PagoMatriculaAlumno: int):
        """
        Sets the id_PagoMatriculaAlumno of this Ingreso.

        :param id_PagoMatriculaAlumno: The id_pagoMatriculaAlumno of this Ingreso.
        :type id_contable: int
        """

        self._id_PagoMatriculaAlumno = id_PagoMatriculaAlumno

    @property
    def fechaMatriculaAlumno(self) -> str:
        """
        Gets the fechaMatriculaAlumno of this Ingreso.

        :return: The fechaMatriculaAlumno of this Ingreso.
        :rtype: str
        """
        return self._fechaMatriculaAlumno

    @fechaMatriculaAlumno.setter
    def fechaMatriculaAlumno(self, fechaMatriculaAlumno: str):
        """
        Sets the fechaMatriculaAlumno of this Ingreso.

        :param fechaMatriculaAlumno: The fechaMatriculaAlumno of this Ingreso.
        :type fechaMatriculaAlumno: str
        """

        self._fechaMatriculaAlumno = fechaMatriculaAlumno

    @property
    def importeMatriculaAlumno(self) -> int:
        """
        Gets the importeMatriculaAlumno of this Ingreso.

        :return: The importeMatriculaAlumno of this Ingreso.
        :rtype: int
        """
        return self._importeMatriculaAlumno

    @importeMatriculaAlumno.setter
    def importeMatriculaAlumno(self, importeMatriculaAlumno: int):
        """
        Sets the importeMatriculaAlumno of this Ingreso.

        :param importeMatriculaAlumno: The importeMatriculaAlumno of this Ingreso.
        :type importeMatriculaAlumno: int
        """

        self._importeMatriculaAlumno = importeMatriculaAlumno

    @property
    def pagoMatriculaAlumnoRealizado(self) -> bool:
        """
        Gets the pagoMatriculaAlumnoRealizado of this Ingreso.

        :return: The pagoMatriculaAlumnoRealizado of this Ingreso.
        :rtype: bool
        """
        return self._pagoMatriculaAlumnoRealizado

    @pagoMatriculaAlumnoRealizado.setter
    def pagoMatriculaAlumnoRealizado(self, pagoMatriculaAlumnoRealizado: bool):
        """
        Sets the pagoMatriculaAlumnoRealizado of this Ingreso.

        :param pagoMatriculaAlumnoRealizado: The pagoMatriculaAlumnoRealizado of this Ingreso.
        :type nombre_contable: bool
        """

        self._pagoMatriculaAlumnoRealizado = pagoMatriculaAlumnoRealizado

    @property
    def id_departamentoContable(self) -> int:
        """
        Gets the id_departamentoContable of this Ingreso.

        :return: The id_departamentoContable of this Ingreso.
        :rtype: int
        """
        return self._id_departamentoContable

    @id_departamentoContable.setter
    def id_departamentoContable(self, id_departamentoContable: int):
        """
        Sets the id_departamentoContable of this Ingreso.

        :param id_departamentoContable: The id_departamentoContable of this Ingreso.
        :type apellidos_contable: int
        """

        self._id_departamentoContable = id_departamentoContable

    @property
    def id_alumno(self) -> int:
        """
        Gets the id_alumno of this Ingreso.

        :return: The id_alumno of this Ingreso.
        :rtype: int
        """
        return self._id_alumno

    @id_alumno.setter
    def id_alumno(self, id_alumno: int):
        """
        Sets the id_alumno of this Contable.

        :param id_alumno: The id_alumno of this Ingreso.
        :type id_alumno: int
        """

        self._id_alumno = id_alumno