# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PAS(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_nominda_pas: int=None, importe_nomina_pas: int=None, pago_nomina_pas_realizado: bool=None, id_departamento_contable: int=None, id_pas: int=None):
        """
        PAS - a model defined in Swagger

        :param id_nominda_pas: The id_nominda_pas of this PAS.
        :type id_nominda_pas: int
        :param importe_nomina_pas: The importe_nomina_pas of this PAS.
        :type importe_nomina_pas: int
        :param pago_nomina_pas_realizado: The pago_nomina_pas_realizado of this PAS.
        :type pago_nomina_pas_realizado: bool
        :param id_departamento_contable: The id_departamento_contable of this PAS.
        :type id_departamento_contable: int
        :param id_pas: The id_pas of this PAS.
        :type id_pas: int
        """
        self.swagger_types = {
            'id_nominda_pas': int,
            'importe_nomina_pas': int,
            'pago_nomina_pas_realizado': bool,
            'id_departamento_contable': int,
            'id_pas': int
        }

        self.attribute_map = {
            'id_nominda_pas': 'id_nomindaPAS',
            'importe_nomina_pas': 'importeNominaPAS',
            'pago_nomina_pas_realizado': 'pagoNominaPASRealizado',
            'id_departamento_contable': 'id_departamentoContable',
            'id_pas': 'id_pas'
        }

        self._id_nominda_pas = id_nominda_pas
        self._importe_nomina_pas = importe_nomina_pas
        self._pago_nomina_pas_realizado = pago_nomina_pas_realizado
        self._id_departamento_contable = id_departamento_contable
        self._id_pas = id_pas

    @classmethod
    def from_dict(cls, dikt) -> 'PAS':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PAS of this PAS.
        :rtype: PAS
        """
        return deserialize_model(dikt, cls)

    @property
    def id_nominda_pas(self) -> int:
        """
        Gets the id_nominda_pas of this PAS.

        :return: The id_nominda_pas of this PAS.
        :rtype: int
        """
        return self._id_nominda_pas

    @id_nominda_pas.setter
    def id_nominda_pas(self, id_nominda_pas: int):
        """
        Sets the id_nominda_pas of this PAS.

        :param id_nominda_pas: The id_nominda_pas of this PAS.
        :type id_nominda_pas: int
        """

        self._id_nominda_pas = id_nominda_pas

    @property
    def importe_nomina_pas(self) -> int:
        """
        Gets the importe_nomina_pas of this PAS.

        :return: The importe_nomina_pas of this PAS.
        :rtype: int
        """
        return self._importe_nomina_pas

    @importe_nomina_pas.setter
    def importe_nomina_pas(self, importe_nomina_pas: int):
        """
        Sets the importe_nomina_pas of this PAS.

        :param importe_nomina_pas: The importe_nomina_pas of this PAS.
        :type importe_nomina_pas: int
        """

        self._importe_nomina_pas = importe_nomina_pas

    @property
    def pago_nomina_pas_realizado(self) -> bool:
        """
        Gets the pago_nomina_pas_realizado of this PAS.

        :return: The pago_nomina_pas_realizado of this PAS.
        :rtype: bool
        """
        return self._pago_nomina_pas_realizado

    @pago_nomina_pas_realizado.setter
    def pago_nomina_pas_realizado(self, pago_nomina_pas_realizado: bool):
        """
        Sets the pago_nomina_pas_realizado of this PAS.

        :param pago_nomina_pas_realizado: The pago_nomina_pas_realizado of this PAS.
        :type pago_nomina_pas_realizado: bool
        """

        self._pago_nomina_pas_realizado = pago_nomina_pas_realizado

    @property
    def id_departamento_contable(self) -> int:
        """
        Gets the id_departamento_contable of this PAS.

        :return: The id_departamento_contable of this PAS.
        :rtype: int
        """
        return self._id_departamento_contable

    @id_departamento_contable.setter
    def id_departamento_contable(self, id_departamento_contable: int):
        """
        Sets the id_departamento_contable of this PAS.

        :param id_departamento_contable: The id_departamento_contable of this PAS.
        :type id_departamento_contable: int
        """

        self._id_departamento_contable = id_departamento_contable

    @property
    def id_pas(self) -> int:
        """
        Gets the id_pas of this PAS.

        :return: The id_pas of this PAS.
        :rtype: int
        """
        return self._id_pas

    @id_pas.setter
    def id_pas(self, id_pas: int):
        """
        Sets the id_pas of this PAS.

        :param id_pas: The id_pas of this PAS.
        :type id_pas: int
        """

        self._id_pas = id_pas

