# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Pago(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, mes: str=None, importe: int=None, pagado: bool=None):
        """
        Pago - a model defined in Swagger

        :param mes: The mes of this Pago.
        :type mes: str
        :param importe: The importe of this Pago.
        :type importe: int
        :param pagado: The pagado of this Pago.
        :type pagado: bool
        """
        self.swagger_types = {
            'mes': str,
            'importe': int,
            'pagado': bool
        }

        self.attribute_map = {
            'mes': 'mes',
            'importe': 'importe',
            'pagado': 'pagado'
        }

        self._mes = mes
        self._importe = importe
        self._pagado = pagado

    @classmethod
    def from_dict(cls, dikt) -> 'Pago':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pago of this Pago.
        :rtype: Pago
        """
        return deserialize_model(dikt, cls)

    @property
    def mes(self) -> str:
        """
        Gets the mes of this Pago.

        :return: The mes of this Pago.
        :rtype: str
        """
        return self._mes

    @mes.setter
    def mes(self, mes: str):
        """
        Sets the mes of this Pago.

        :param mes: The mes of this Pago.
        :type mes: str
        """

        self._mes = mes

    @property
    def importe(self) -> int:
        """
        Gets the importe of this Pago.

        :return: The importe of this Pago.
        :rtype: int
        """
        return self._importe

    @importe.setter
    def importe(self, importe: int):
        """
        Sets the importe of this Pago.

        :param importe: The importe of this Pago.
        :type importe: int
        """

        self._importe = importe

    @property
    def pagado(self) -> bool:
        """
        Gets the pagado of this Pago.

        :return: The pagado of this Pago.
        :rtype: bool
        """
        return self._pagado

    @pagado.setter
    def pagado(self, pagado: bool):
        """
        Sets the pagado of this Pago.

        :param pagado: The pagado of this Pago.
        :type pagado: bool
        """

        self._pagado = pagado

